"""Local-first MARK runtime SDK."""

from mark._version import __version__
from mark.agent import AgentResult, AgentRun, MarkAgent
from mark.context import ContextBundle, ContextBuilder
from mark.embeddings import CachedEmbeddingProvider, EmbeddingProvider, HashEmbeddingProvider
from mark.index import VectorIndex, VectorSearchResult
from mark.intelligence import (
    ContextualCompressor,
    KeywordQueryExpander,
    LLMContextualCompressor,
    LLMQueryExpander,
    NoopCompressor,
    NoopQueryExpander,
    QueryExpander,
    RetrievalPipeline,
    RetrievalPolicy,
    RetrievalResult,
    SessionFilter,
    SimpleWindowCompressor,
)
from mark.memory import (
    BlockChain,
    BlockGraph,
    BlockVerification,
    ChainVerification,
    ClusterResult,
    ConversationMemory,
    DeduplicationConsolidator,
    DeduplicationResult,
    GlobalMemoryBus,
    GraphNeighborhood,
    MarkMemory,
    MarkRuntime,
    MemoryBlock,
    MemoryManager,
    MemoryRecord,
    MemoryState,
    MemoryWriteRejection,
    ObserveEvent,
    ObserveResult,
    SimpleMemory,
    SimpleBlock,
)
from mark.intelligence import (
    DeterministicExtractor,
    ExtractionMerger,
    ExtractionResult,
    ExtractedEntity,
    ExtractedRelation,
    LLMStructuredExtractor,
    StructuredExtraction,
)
from mark.plugins import HOOK_OBSERVE_EVENT
from mark.policies import PolicyDecision, PolicyRegistry
from mark.runtime import Mark, MarkConfig
from mark.middlewares.skills import AgentPersona, SkillRegistry, agent_skill, list_packaged_skills, load_skill_text
from mark.store import JsonMemoryStore, LocalMemoryStore, SessionActivityLog
from mark.types import BlockLink, BlockStatus
from mark.types.llm import LLMProvider

_LAZY_EXPORTS = {
    "AuditEntry": "mark.middlewares.governance",
    "BaseMiddleware": "mark.middlewares.base",
    "BusMessage": "mark.middlewares.trust_bus",
    "BusSnapshot": "mark.middlewares.trust_bus",
    "BusSubscription": "mark.middlewares.trust_bus",
    "CharacterMemory": "mark.middlewares.media_continuity",
    "CloudSync": "mark.middlewares.sync",
    "CompressionMiddleware": "mark.middlewares.compression",
    "ConsolidationGate": "mark.middlewares.governance",
    "ConsolidationGateResult": "mark.middlewares.governance",
    "ContentSanitizer": "mark.middlewares.governance",
    "DuplicateHashGate": "mark.middlewares.governance",
    "EventReplayer": "mark.middlewares.observability",
    "FailureFilter": "mark.middlewares.governance",
    "GapHealingMiddleware": "mark.middlewares.gap_healing",
    "GateResult": "mark.middlewares.governance",
    "GovernanceAuditLog": "mark.middlewares.governance",
    "GovernanceMiddleware": "mark.middlewares.governance",
    "LifecycleMiddleware": "mark.middlewares.lifecycle",
    "LocalTracer": "mark.middlewares.observability",
    "LocationMemory": "mark.middlewares.media_continuity",
    "MarkMiddleware": "mark.middlewares.base",
    "MediaContinuityMiddleware": "mark.middlewares.media_continuity",
    "MiddlewareContext": "mark.middlewares.base",
    "MiddlewareStack": "mark.middlewares.base",
    "ObjectMemory": "mark.middlewares.media_continuity",
    "ObservabilityMiddleware": "mark.middlewares.observability",
    "ObserveMiddleware": "mark.middlewares.observe",
    "PublisherTrust": "mark.middlewares.trust_bus",
    "QueryExpansionMiddleware": "mark.middlewares.query_expansion",
    "RecallMiddleware": "mark.middlewares.recall",
    "SkillMiddleware": "mark.middlewares.skills",
    "RuntimeEvent": "mark.middlewares.observability",
    "RuntimeEventLog": "mark.middlewares.observability",
    "SandboxMiddleware": "mark.middlewares.sandbox",
    "SessionMemory": "mark.middlewares.media_continuity",
    "SessionTrace": "mark.middlewares.observability",
    "SyncDelta": "mark.middlewares.sync",
    "SyncMiddleware": "mark.middlewares.sync",
    "SyncMode": "mark.middlewares.sync",
    "SyncOptions": "mark.middlewares.sync",
    "SyncStats": "mark.middlewares.sync",
    "TrustAwareGlobalMemoryBus": "mark.middlewares.trust_bus",
    "TrustBusMiddleware": "mark.middlewares.trust_bus",
    "ValidationGate": "mark.middlewares.governance",
    "WorldBibleMemory": "mark.middlewares.media_continuity",
}


def __getattr__(name: str):
    if name not in _LAZY_EXPORTS:
        raise AttributeError(f"module 'mark' has no attribute {name!r}")
    from importlib import import_module

    module = import_module(_LAZY_EXPORTS[name])
    value = getattr(module, name)
    globals()[name] = value
    return value

__all__ = [
    "AgentResult",
    "AgentRun",
    "AgentPersona",
    "agent_skill",
    "list_packaged_skills",
    "load_skill_text",
    "AuditEntry",
    "BaseMiddleware",
    "BlockChain",
    "BlockGraph",
    "BlockLink",
    "BlockStatus",
    "BlockVerification",
    "ChainVerification",
    "BusMessage",
    "BusSnapshot",
    "BusSubscription",
    "CachedEmbeddingProvider",
    "CharacterMemory",
    "ClusterResult",
    "ConsolidationGate",
    "ConsolidationGateResult",
    "ContentSanitizer",
    "ConversationMemory",
    "ContextBuilder",
    "ContextBundle",
    "ContextualCompressor",
    "CompressionMiddleware",
    "DeduplicationConsolidator",
    "DeduplicationResult",
    "DeterministicExtractor",
    "DuplicateHashGate",
    "CloudSync",
    "EmbeddingProvider",
    "EventReplayer",
    "FailureFilter",
    "GapHealingMiddleware",
    "GovernanceMiddleware",
    "GateResult",
    "GovernanceAuditLog",
    "ExtractionMerger",
    "ExtractionResult",
    "ExtractedEntity",
    "ExtractedRelation",
    "GlobalMemoryBus",
    "GraphNeighborhood",
    "HashEmbeddingProvider",
    "HOOK_OBSERVE_EVENT",
    "KeywordQueryExpander",
    "JsonMemoryStore",
    "LLMContextualCompressor",
    "LLMProvider",
    "LLMQueryExpander",
    "LLMStructuredExtractor",
    "LifecycleMiddleware",
    "LocalMemoryStore",
    "LocalTracer",
    "LocationMemory",
    "Mark",
    "MarkAgent",
    "MarkConfig",
    "MarkMiddleware",
    "MediaContinuityMiddleware",
    "MarkMemory",
    "MarkRuntime",
    "MemoryBlock",
    "MemoryManager",
    "MemoryRecord",
    "MemoryState",
    "MemoryWriteRejection",
    "MiddlewareContext",
    "MiddlewareStack",
    "NoopCompressor",
    "NoopQueryExpander",
    "ObjectMemory",
    "ObserveEvent",
    "ObservabilityMiddleware",
    "ObserveMiddleware",
    "ObserveResult",
    "PolicyDecision",
    "PolicyRegistry",
    "PublisherTrust",
    "QueryExpansionMiddleware",
    "QueryExpander",
    "RetrievalPipeline",
    "RuntimeEvent",
    "RuntimeEventLog",
    "RetrievalPolicy",
    "RetrievalResult",
    "RecallMiddleware",
    "SandboxMiddleware",
    "SessionActivityLog",
    "SessionTrace",
    "SyncMode",
    "SyncDelta",
    "SyncMiddleware",
    "TrustBusMiddleware",
    "SyncOptions",
    "SyncStats",
    "SessionFilter",
    "SessionMemory",
    "SimpleBlock",
    "SimpleMemory",
    "SimpleWindowCompressor",
    "StructuredExtraction",
    "SkillMiddleware",
    "SkillRegistry",
    "TrustAwareGlobalMemoryBus",
    "ValidationGate",
    "VectorIndex",
    "VectorSearchResult",
    "WorldBibleMemory",
    "__version__",
]
